# docker-compose.yml
version: "3.9"

services:
  db:
    image: mysql:8.0.33
    container_name: mysql-container
    ports:
      - "3306:3306"  # Exposing container port 3306 to host port 3306
    environment:
      MYSQL_ROOT_PASSWORD: kjelhus123
      MYSQL_DATABASE: geolife_db
      MYSQL_USER: root
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent data storage
    networks:
      - backend

volumes:
  mysql_data:  # Volume to persist MySQL data

networks:
  backend:  # Network for communication between services